[package]
name = "turtle"
version = "0.1.0"
authors = ["Pham Le Quang <phamlequang@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.4"
serde = "1.0.82"
serde_derive = "1.0.82"
subprocess = "0.1.18"
termion = "1.5.1"
rustyline = "3.0.0"
ctrlc = "3.1.1"
dirs = "1.0.4"
